### ISSUE TITLE
Add Required Field Indicators

### ISSUE THREAD

**Issue by joebeernink** [joebeernink/TrashMob#174]
Required fields on all forms should have a required field indicator

**Comment by hanoelleb** [comment]
Hi I was wondering if I could help with this? This would be on both the create event form and the contact form correct?

**Comment by joebeernink** [comment]
Hi, sorry I missed this message. I'd love to have you take a shot at this! 

There's the create event, edit event, and contact form. Someday I want to consolidate the create and edit form, but I haven't had time yet.

**Comment by codeHysteria28** [comment]
Hi. This issue should be marked as completed as I've checked like create event, edit event and so on and all the fields seems to have "required" attribute at the place.

**Comment by joebeernink** [comment]
Would like the presence of the required field indicator to show a visible indicator on the form that the field is required.

**Comment by joebeernink** [comment]
Done
