### ISSUE TITLE
Allow user to add an event to their calendars

### ISSUE THREAD

**Issue by joebeernink** [joebeernink/TrashMob#209]
Support various calendar formats. Add button/dropdown to event details page

**Comment by codeHysteria28** [comment]
Hi. Just added an update to this issue. I created a functionality for this. Supporting Apple, Outlook, Google, Yahoo calendars. Please see commit here for details.

https://github.com/joebeernink/TrashMob/commit/3918aceb9355cdbf0c5312630cb9eeb8dc19c44a
