### ISSUE TITLE
Add Site Help functionality

### ISSUE THREAD

**Issue by joebeernink** [joebeernink/TrashMob#210]
How to create an event
How to delete an event
How to change the location of an event
etc.

**Comment by joebeernink** [comment]
Will add YouTube videos when completed

**Comment by MattEEvans** [comment]
I can help out with this, but sign in doesn't go smoothly for me. I land on the Partners page with a "Loading..." message. When I go back to the home page, I do appear to be signed in, though. We'll want to wait until the latest updates are on the site before we create the videos.

**Comment by joebeernink** [comment]
Still waiting on the site updates so we have the most recent designs in the videos.
